using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class soundScript : MonoBehaviour // Script governing the conditional sounds across the map
{
    // Start is called before the first frame update (Auto generated by the IDE)
    public AudioSource sfx; // variable for the audio
    public float maxTime = 15f; // how long the sound plays
    private bool isPlaying = false; 
    private float timer; //

    private void OnTriggerEnter(Collider other) { // PLay the sound once the player collides with the trigger, and isPlayng is false
        if (other.CompareTag("Player") && !isPlaying) {
            isPlaying = true;
            sfx.Play();
            timer = 0f; // Initialise the timer
            }
    }

    
    void Update() // Updates every frame
    {
        if (isPlaying) {
            timer = timer + Time.deltaTime; // Timer starts
            if (timer >= maxTime) { // Once the timer exceeds the maximum time, stop playing and reset the boolean flag
                sfx.Stop();
                isPlaying = false;
            }
        }
        
    }
}
